
# 使用默认的 GitLab Pages 镜像
image: alpine:latest

# 设置缓存
cache:
  paths:
    - public/

# 定义构建 job
pages:
  stage: deploy
  script:
    # 创建 public 文件夹并将项目的所有文件复制到其中
    - mkdir public
    - cp -r * public/  # 将项目文件复制到 public 文件夹
  artifacts:
    paths:
      - public  # 确保 public 文件夹在 artifacts 中
  only:
    - main  # 只在 main 分支上运行
