# 使用默认的 GitLab Pages 镜像
image: alpine:latest

# 定义 pages 任务
pages:
  stage: deploy
  script:
    # 创建 public 文件夹
    - mkdir -p public
    # 使用 rsync 排除 public 文件夹自身，复制所有内容到 public 中
    - apk add --no-cache rsync  # 安装 rsync
    - rsync -av --exclude='public' . public/
  artifacts:
    paths:
      - public  # 指定 public 文件夹作为 GitLab Pages 发布目录
  only:
    - main  # 仅在 main 分支上执行
